import { TechLogo } from "@/types/project.types";

const TECH_STACK: TechLogo[] = [
  { name: "Azure", icon: "☁️" },
  { name: "Azure DevOps", icon: "☁️" },
  { name: "SQL", icon: "🗄️" },
  { name: "Bash", icon: "💻" },
  { name: "C#", icon: "#️⃣" },
  { name: ".NET", icon: "🔷" },
  { name: "CSS3", icon: "🎨" },
  { name: "Docker", icon: "🐳" },
  { name: "Firebase", icon: "🔥" },
  { name: "GitHub", icon: "🐙" },
  { name: "GitLab", icon: "🦊" },
  { name: "GraphQL", icon: "◈" },
  { name: "HTML5", icon: "📄" },
  { name: "JavaScript", icon: "⚡" },
  { name: "Kubernetes", icon: "☸️" },
  { name: "MongoDB", icon: "🍃" },
  { name: "Swagger", icon: "📋" },
  { name: "Next.js", icon: "▲" },
  { name: "Vercel", icon: "▼" },
  { name: "Node.js", icon: "🟢" },
  { name: "PHP", icon: "🐘" },
  { name: "Postman", icon: "📮" },
  { name: "RabbitMQ", icon: "🐰" },
  { name: "React", icon: "⚛️" },
  { name: "TypeScript", icon: "🔷" },
  { name: "Angular", icon: "💚" },
  { name: "Python", icon: "💚" },
  { name: "OpenAI API", icon: "💚" },
  { name: "Rest", icon: "💚" },
  { name: "TensorFlow", icon: "💚" },
  { name: "Codex CLI", icon: "💚" },
  { name: "PostgreSQL", icon: "💚" },
  { name: "MySQL", icon: "💚" },
  { name: "Vector Databases", icon: "💚" },
];

export default TECH_STACK;
